site_name: Mikkel Krüger Larsen - Professionsbachelor i it-sikkerhed
nav:
  - Hjem: index.md
  - Skabelon: Skabelon.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  shortcuts:
    help: 191
    next: 78
    previous: 80
    search: 83
  
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mikk391e
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/Mikk391e
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mikkel-kr%C3%BCger-larsen-6061b385/
    - icon: fontawesome/solid/paper-plane
      link: mikkelkrugelarsen@gmail.com
copyright: Copyright &copy; 2025 Mikkel Krüger Larsen

    